# Generated by Django 5.2 on 2025-05-08 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена пользователем'), ('rejected', 'Отклонена админом')], default='pending', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('location_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_start', to='locations.location')),
                ('location_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_end', to='locations.location')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
