# Generated by Django 5.2 on 2025-05-08 10:12

import autoslug.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(default='brands_images/default.jpg', upload_to='brands_images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в день')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скидка (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(max_length=150, verbose_name='модель')),
                ('year_released', models.DateField(verbose_name='год выпуска')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='описание')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='get_slug_source', unique=True)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='объем двигателя')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет кузова')),
                ('body_type', models.CharField(blank=True, choices=[('седан', 'седан'), ('купе', 'купе'), ('хетчбэк', 'хетчбэк'), ('кроссовер', 'кроссовер'), ('джип', 'джип')], default='седан', null=True, verbose_name='кузов')),
                ('state_number', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='гос номер')),
                ('available', models.BooleanField(default=True, verbose_name='доступна для аренды')),
                ('image1', models.ImageField(default='car_images/default.jpg', upload_to='car_images/')),
                ('image2', models.ImageField(blank=True, upload_to='car_images/')),
                ('image3', models.ImageField(blank=True, upload_to='car_images/')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='локация')),
                ('tariff_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.tariffplan', verbose_name='тарифный план')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-id'],
            },
        ),
    ]
