# Generated by Django 5.2 on 2025-05-09 10:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='get_slug_source', editable=False, populate_from='get_slug_source'),
        ),
    ]
