# Generated by Django 5.2 on 2025-05-09 10:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug_source', unique=True),
        ),
    ]
