# Generated by Django 5.2 on 2025-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='picture',
            field=models.ImageField(default='brands_images/pictures/default.png', null=True, upload_to='brands_images/pictures'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(default='brands_images/default.jpg', upload_to='brands_images/images'),
        ),
    ]
