# Generated by Django 5.2 on 2025-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_brand_picture_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.FileField(default='brands_images/logo/default.png', null=True, upload_to='brands_images/logo/'),
        ),
    ]
