# Generated by Django 5.2 on 2025-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_released',
            field=models.IntegerField(verbose_name='год выпуска'),
        ),
    ]
