# Generated by Django 5.2 on 2025-05-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(verbose_name='путь к аватару'),
        ),
    ]
